Repository ADAM-2022/Module-MeetUp, pull requests merged in 2022-09, with the labels that each got.

#3 [Feature] SwipeGesture 추가 및 NavigationBar 숨김
  Module-MeetUP/Module-MeetUP.xcodeproj/project.pbxproj
  Module-MeetUP/Module-MeetUP/Global/Extension/ViewExtension.swift
Labels: feature

#8 Feature/post detail view UI
  Module-MeetUP/Module-MeetUP.xcodeproj/project.pbxproj
  Module-MeetUP/Module-MeetUP/App/Module_MeetUPApp.swift
  Module-MeetUP/Module-MeetUP/Global/DeviceInfo.swift
  Module-MeetUP/Module-MeetUP/Screens/MainView.swift
  Module-MeetUP/Module-MeetUP/Screens/PostDetailView/PostDetailStateHolder.swift
  Module-MeetUP/Module-MeetUP/Screens/PostDetailView/PostDetailView.swift
  Module-MeetUP/Module-MeetUP/Screens/PostDetailView/PostDetailViewTemp.swift
  Module-MeetUP/Module-MeetUP/Screens/PostDetailView/ViewComponents/PostDetailBackButton.swift
  Module-MeetUP/Module-MeetUP/Screens/PostDetailView/ViewComponents/PostDetailBodyArea.swift
  Module-MeetUP/Module-MeetUP/Screens/PostDetailView/ViewComponents/PostDetailInfoArea.swift
  Module-MeetUP/Module-MeetUP/Screens/PostDetailView/ViewComponents/PostDetailTitleArea.swift
Labels: feature

#10 [Feature] 당겨서 새로고침 UI 추가 및 #4 PR 수정사항 반영
  Module-MeetUP/Module-MeetUP.xcodeproj/project.pbxproj
  Module-MeetUP/Module-MeetUP/Screens/PostsListView/PostsListView.swift
  Module-MeetUP/Module-MeetUP/Screens/PostsListView/PostsListViewComponents/BackButtonView.swift
  Module-MeetUP/Module-MeetUP/Screens/PostsListView/PostsListViewComponents/FloatingButtonView.swift
  Module-MeetUP/Module-MeetUP/Screens/PostsListView/PostsListViewComponents/PostCellView.swift
  Module-MeetUP/Module-MeetUP/Screens/PostsListView/PostsListViewComponents/RefreshableScrollView.swift
  Module-MeetUP/Module-MeetUP/Screens/PostsListView/PostsListViewComponents/SearchButton.swift
Labels: feature, refact

#12 feat: #6 Combine 네트워크 모듈 생성
  Module-MeetUP/Module-MeetUP.xcodeproj/project.pbxproj
  Module-MeetUP/Module-MeetUP/Model/Post.swift
  Module-MeetUP/Module-MeetUP/NetworkModule/MeetUpNetwork.swift
  Module-MeetUP/Module-MeetUP/NetworkModule/MeetUpNetworkService.swift
  Module-MeetUP/Module-MeetUP/NetworkModule/NetworkModuleTemp.swift
  Module-MeetUP/Module-MeetUP/Resources/Assets.xcassets/example.imageset/Contents.json
  Module-MeetUP/Module-MeetUP/Resources/Assets.xcassets/example.imageset/example.jpeg
Labels: feature

#14 [Fix] PostsListView TopPadding 값 수정
  Module-MeetUP/Module-MeetUP/Screens/PostsListView/PostsListView.swift
  Module-MeetUP/Module-MeetUP/Screens/PostsListView/PostsListViewComponents/PostsListTitleView.swift
Labels: fix

#16 [Feat] SearchView UI 구현
  Module-MeetUP/Module-MeetUP.xcodeproj/project.pbxproj
  Module-MeetUP/Module-MeetUP/Screens/Search/SearchView.swift
  Module-MeetUP/Module-MeetUP/Screens/Search/SearchViewComponents/RecentSearchHistoryListView.swift
  Module-MeetUP/Module-MeetUP/Screens/Search/SearchViewComponents/SearchBackButtonView.swift
  Module-MeetUP/Module-MeetUP/Screens/Search/SearchViewComponents/SearchBarView.swift
  Module-MeetUP/Module-MeetUP/Screens/Search/SearchViewComponents/SearchViewTitle.swift
Labels: feature
